<a href="https://colab.research.google.com/github/Veera9014/practice-data-science-code/blob/main/Pandas_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Salaries.csv")

In [ ]:
df.head()

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [ ]:
df.shape

(51, 6)

In [ ]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [ ]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [ ]:
df.tail(10)

         rank discipline  phd  service     sex  salary
41   AsstProf          A    4        2  Female   77500
42       Prof          A   28        7  Female  116450
43   AsstProf          A    8        3  Female   78500
44  AssocProf          B   12        9  Female   71065
45       Prof          B   24       15  Female  161101
46       Prof          B   18       10  Female  105450
47  AssocProf          B   19        6  Female  104542
48       Prof          B   17       17  Female  124312
49       Prof          A   28       14  Female  109954
50       Prof          A   23       15  Female  109646

In [ ]:
df.axes

[RangeIndex(start=0, stop=51, step=1),
 Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')]

In [ ]:
df.describe()

             phd    service         salary
count  51.000000  51.000000      51.000000
mean   17.705882  12.960784  106278.568627
std    12.090152  11.615439   27957.854794
min     1.000000   0.000000   63100.000000
25%     8.000000   3.000000   86500.000000
50%    17.000000  10.000000  103994.000000
75%    24.500000  20.000000  123041.500000
max    56.000000  49.000000  186960.000000

In [ ]:
df.min()

rank          AssocProf
discipline            A
phd                   1
service               0
sex              Female
salary            63100
dtype: object

In [ ]:
df.discipline.unique()

array(['B', 'A'], dtype=object)

In [ ]:
df.discipline.value_counts()

discipline
B    28
A    23
Name: count, dtype: int64

In [ ]:
df['rank'].unique()

array(['Prof', 'AssocProf', 'AsstProf'], dtype=object)

In [ ]:
df['rank'].value_counts()

rank
Prof         26
AsstProf     16
AssocProf     9
Name: count, dtype: int64

In [ ]:
df.describe()

             phd    service         salary
count  51.000000  51.000000      51.000000
mean   17.705882  12.960784  106278.568627
std    12.090152  11.615439   27957.854794
min     1.000000   0.000000   63100.000000
25%     8.000000   3.000000   86500.000000
50%    17.000000  10.000000  103994.000000
75%    24.500000  20.000000  123041.500000
max    56.000000  49.000000  186960.000000

In [ ]:
#Selecting a column
df.salary

0     186960
1     122400
2      81285
3     134778
4      88000
5     150480
6      75044
7      92000
8     107300
9     150500
10     92000
11    103106
12     73000
13     85000
14     91100
15     91300
16    123683
17    107008
18    155750
19    119800
20    146856
21     91000
22    137000
23     74830
24    140096
25     74692
26    103613
27    111512
28     97032
29    127512
30    105000
31     73500
32     72500
33    144651
34    103994
35     92000
36     91000
37     73300
38    117555
39     63100
40     90450
41     77500
42    116450
43     78500
44     71065
45    161101
46    105450
47    104542
48    124312
49    109954
50    109646
Name: salary, dtype: int64

In [ ]:
df['salary']

0     186960
1     122400
2      81285
3     134778
4      88000
5     150480
6      75044
7      92000
8     107300
9     150500
10     92000
11    103106
12     73000
13     85000
14     91100
15     91300
16    123683
17    107008
18    155750
19    119800
20    146856
21     91000
22    137000
23     74830
24    140096
25     74692
26    103613
27    111512
28     97032
29    127512
30    105000
31     73500
32     72500
33    144651
34    103994
35     92000
36     91000
37     73300
38    117555
39     63100
40     90450
41     77500
42    116450
43     78500
44     71065
45    161101
46    105450
47    104542
48    124312
49    109954
50    109646
Name: salary, dtype: int64

In [ ]:
df[['salary','sex','discipline']]

    salary     sex discipline
0   186960    Male          B
1   122400    Male          A
2    81285    Male          A
3   134778    Male          B
4    88000    Male          B
5   150480    Male          B
6    75044    Male          B
7    92000    Male          B
8   107300    Male          A
9   150500    Male          A
10   92000    Male          B
11  103106    Male          A
12   73000    Male          A
13   85000    Male          A
14   91100    Male          A
15   91300    Male          B
16  123683    Male          B
17  107008    Male          B
18  155750    Male          B
19  119800    Male          B
20  146856    Male          B
21   91000    Male          B
22  137000  Female          A
23   74830  Female          A
24  140096  Female          B
25   74692  Female          B
26  103613  Female          B
27  111512  Female          B
28   97032  Female          B
29  127512  Female          B
30  105000  Female          A
31   73500  Female          A
32   72500  Female          A
33  144651  Female          B
34  103994  Female          B
35   92000  Female          B
36   91000  Female          A
37   73300  Female          A
38  117555  Female          A
39   63100  Female          A
40   90450  Female          A
41   77500  Female          A
42  116450  Female          A
43   78500  Female          A
44   71065  Female          B
45  161101  Female          B
46  105450  Female          B
47  104542  Female          B
48  124312  Female          B
49  109954  Female          A
50  109646  Female          A

In [ ]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

Calculate the basic statistics for the Phd column;

Find how many values in the Phd column (use count method);

Calculate the average Phd;

In [ ]:
df.phd.var()

146.17176470588237

In [ ]:
df.phd.count()

51

In [ ]:
df.phd.mean()

17.705882352941178

In [ ]:
groupby=df.groupby(['rank'])

In [ ]:
for i,j in groupby:
    print(i)
    print(j)

('AssocProf',)
         rank discipline  phd  service     sex  salary
2   AssocProf          A   20       17    Male   81285
17  AssocProf          B    9        7    Male  107008
19  AssocProf          B   12        8    Male  119800
23  AssocProf          A   13        8  Female   74830
26  AssocProf          B   11       11  Female  103613
34  AssocProf          B   12       10  Female  103994
37  AssocProf          A   26       24  Female   73300
44  AssocProf          B   12        9  Female   71065
47  AssocProf          B   19        6  Female  104542
('AsstProf',)
        rank discipline  phd  service     sex  salary
4   AsstProf          B    1        0    Male   88000
6   AsstProf          B    8        3    Male   75044
7   AsstProf          B    4        0    Male   92000
10  AsstProf          B    4        4    Male   92000
12  AsstProf          A    4        2    Male   73000
13  AsstProf          A    2        0    Male   85000
15  AsstProf          B    7        2    Male   91300
21  AsstProf          B    4        3    Male   91000
25  AsstProf          B   11        3  Female   74692
28  AsstProf          B   10        5  Female   97032
31  AsstProf          A    5        3  Female   73500
32  AsstProf          A    3        1  Female   72500
35  AsstProf          B    3        3  Female   92000
39  AsstProf          A    7        6  Female   63100
41  AsstProf          A    4        2  Female   77500
43  AsstProf          A    8        3  Female   78500
('Prof',)
    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   20       20    Male  122400
3   Prof          B   23       23    Male  134778
5   Prof          B   17        3    Male  150480
8   Prof          A   19        7    Male  107300
9   Prof          A   29       27    Male  150500
11  Prof          A   33       30    Male  103106
14  Prof          A   30       23    Male   91100
16  Prof          B   21       20    Male  123683
18  Prof          B   22       21    Male  155750
20  Prof          B   45       45    Male  146856
22  Prof          A   39       36  Female  137000
24  Prof          B   25       25  Female  140096
27  Prof          B   17       17  Female  111512
29  Prof          B   20       14  Female  127512
30  Prof          A   12        0  Female  105000
33  Prof          B   36       26  Female  144651
36  Prof          A   29       27  Female   91000
38  Prof          A   36       19  Female  117555
40  Prof          A   17       11  Female   90450
42  Prof          A   28        7  Female  116450
45  Prof          B   24       15  Female  161101
46  Prof          B   18       10  Female  105450
48  Prof          B   17       17  Female  124312
49  Prof          A   28       14  Female  109954
50  Prof          A   23       15  Female  109646

In [ ]:
df.groupby('rank').mean salary()

SyntaxError: invalid syntax (<ipython-input-3-958093722ffd>, line 1)

In [ ]:
df.groupby('rank')[['salary','phd']].mean()

                  salary        phd
rank
AssocProf   93270.777778  14.888889
AsstProf    82260.500000   5.312500
Prof       125561.615385  26.307692

In [ ]:
df.groupby('sex')['service'].mean()[0]

<ipython-input-49-e255aa065e3f>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.groupby('sex')['service'].mean()[0]

11.96551724137931

In [ ]:
grouped=df.groupby('rank')

In [ ]:
type(grouped)

pandas.core.groupby.generic.DataFrameGroupBy

In [ ]:
df.salary>120000

0      True
1      True
2     False
3      True
4     False
5      True
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17    False
18     True
19    False
20     True
21    False
22     True
23    False
24     True
25    False
26    False
27    False
28    False
29     True
30    False
31    False
32    False
33     True
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45     True
46    False
47    False
48     True
49    False
50    False
Name: salary, dtype: bool

In [ ]:
df[df.salary>120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   20       20    Male  122400
3   Prof          B   23       23    Male  134778
5   Prof          B   17        3    Male  150480
9   Prof          A   29       27    Male  150500
16  Prof          B   21       20    Male  123683
18  Prof          B   22       21    Male  155750
20  Prof          B   45       45    Male  146856
22  Prof          A   39       36  Female  137000
24  Prof          B   25       25  Female  140096
29  Prof          B   20       14  Female  127512
33  Prof          B   36       26  Female  144651
45  Prof          B   24       15  Female  161101
48  Prof          B   17       17  Female  124312

In [ ]:
df[df.salary==150500]

   rank discipline  phd  service   sex  salary
9  Prof          A   29       27  Male  150500

In [ ]:
df[df.salary>150500]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
18  Prof          B   22       21    Male  155750
45  Prof          B   24       15  Female  161101

In [ ]:
df.head()

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [ ]:
df.iloc[1:4, 0:3]

        rank discipline  phd
1       Prof          A   20
2  AssocProf          A   20
3       Prof          B   23

In [ ]:
df.iloc[0:10,0:3]

        rank discipline  phd
0       Prof          B   56
1       Prof          A   20
2  AssocProf          A   20
3       Prof          B   23
4   AsstProf          B    1
5       Prof          B   17
6   AsstProf          B    8
7   AsstProf          B    4
8       Prof          A   19
9       Prof          A   29

In [ ]:
df.iloc[0:2,]

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   20       20  Male  122400

In [ ]:
df.iloc[:,-4]

0     56
1     20
2     20
3     23
4      1
5     17
6      8
7      4
8     19
9     29
10     4
11    33
12     4
13     2
14    30
15     7
16    21
17     9
18    22
19    12
20    45
21     4
22    39
23    13
24    25
25    11
26    11
27    17
28    10
29    20
30    12
31     5
32     3
33    36
34    12
35     3
36    29
37    26
38    36
39     7
40    17
41     4
42    28
43     8
44    12
45    24
46    18
47    19
48    17
49    28
50    23
Name: phd, dtype: int64

In [ ]:
df.loc[:,'phd':'salary']

    phd  service     sex  salary
0    56       49    Male  186960
1    20       20    Male  122400
2    20       17    Male   81285
3    23       23    Male  134778
4     1        0    Male   88000
5    17        3    Male  150480
6     8        3    Male   75044
7     4        0    Male   92000
8    19        7    Male  107300
9    29       27    Male  150500
10    4        4    Male   92000
11   33       30    Male  103106
12    4        2    Male   73000
13    2        0    Male   85000
14   30       23    Male   91100
15    7        2    Male   91300
16   21       20    Male  123683
17    9        7    Male  107008
18   22       21    Male  155750
19   12        8    Male  119800
20   45       45    Male  146856
21    4        3    Male   91000
22   39       36  Female  137000
23   13        8  Female   74830
24   25       25  Female  140096
25   11        3  Female   74692
26   11       11  Female  103613
27   17       17  Female  111512
28   10        5  Female   97032
29   20       14  Female  127512
30   12        0  Female  105000
31    5        3  Female   73500
32    3        1  Female   72500
33   36       26  Female  144651
34   12       10  Female  103994
35    3        3  Female   92000
36   29       27  Female   91000
37   26       24  Female   73300
38   36       19  Female  117555
39    7        6  Female   63100
40   17       11  Female   90450
41    4        2  Female   77500
42   28        7  Female  116450
43    8        3  Female   78500
44   12        9  Female   71065
45   24       15  Female  161101
46   18       10  Female  105450
47   19        6  Female  104542
48   17       17  Female  124312
49   28       14  Female  109954
50   23       15  Female  109646

In [ ]:
df.loc[10:21,'phd':'salary']

    phd  service   sex  salary
10    4        4  Male   92000
11   33       30  Male  103106
12    4        2  Male   73000
13    2        0  Male   85000
14   30       23  Male   91100
15    7        2  Male   91300
16   21       20  Male  123683
17    9        7  Male  107008
18   22       21  Male  155750
19   12        8  Male  119800
20   45       45  Male  146856
21    4        3  Male   91000

In [ ]:
df.loc[:,['salary','phd']]

    salary  phd
0   186960   56
1   122400   20
2    81285   20
3   134778   23
4    88000    1
5   150480   17
6    75044    8
7    92000    4
8   107300   19
9   150500   29
10   92000    4
11  103106   33
12   73000    4
13   85000    2
14   91100   30
15   91300    7
16  123683   21
17  107008    9
18  155750   22
19  119800   12
20  146856   45
21   91000    4
22  137000   39
23   74830   13
24  140096   25
25   74692   11
26  103613   11
27  111512   17
28   97032   10
29  127512   20
30  105000   12
31   73500    5
32   72500    3
33  144651   36
34  103994   12
35   92000    3
36   91000   29
37   73300   26
38  117555   36
39   63100    7
40   90450   17
41   77500    4
42  116450   28
43   78500    8
44   71065   12
45  161101   24
46  105450   18
47  104542   19
48  124312   17
49  109954   28
50  109646   23

In [ ]:
df.loc[20:30,['salary','rank']]

    salary       rank
20  146856       Prof
21   91000   AsstProf
22  137000       Prof
23   74830  AssocProf
24  140096       Prof
25   74692   AsstProf
26  103613  AssocProf
27  111512       Prof
28   97032   AsstProf
29  127512       Prof
30  105000       Prof

In [ ]:
df.iloc[30:36,[3,0,5]]

    service       rank  salary
30        0       Prof  105000
31        3   AsstProf   73500
32        1   AsstProf   72500
33       26       Prof  144651
34       10  AssocProf  103994
35        3   AsstProf   92000

In [ ]:
df.loc[30:40,'phd':'salary']

    phd  service     sex  salary
30   12        0  Female  105000
31    5        3  Female   73500
32    3        1  Female   72500
33   36       26  Female  144651
34   12       10  Female  103994
35    3        3  Female   92000
36   29       27  Female   91000
37   26       24  Female   73300
38   36       19  Female  117555
39    7        6  Female   63100
40   17       11  Female   90450

In [ ]:
df.salary.skew()

0.724123000057386

In [ ]:
df.phd.skew()

0.8701751073917512

In [ ]:
df.phd.kurt()

0.7963045381022211

In [ ]:
df.salary.kurt()

0.07799441064831525

In [ ]:
df.salary.median()

103994.0

In [ ]:
df.salary.mean()

106278.56862745098

In [ ]:
df.salary.mode()[0]

92000

In [ ]:
df['rank'].mode()[0][3]

'f'

In [ ]:
df.salary.mode()[0]

92000

In [ ]:
df['sex'].mode()

0    Female
Name: sex, dtype: object